config/routes.rb
Flitter::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  get ':users/:username', :controller => "home", :action => "show"

  match '/:users/:username/do_follow', :controller => 'home', :action => "do_follow"

  resources :sessions

  resources :twits

  resources :users

  root :to => "home#index"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id

  belongs_to :user
  belongs_to :friend, :class_name => 'User'
  validates_uniqueness_of :friend_id, :scope => :user_id
  validates_presence_of  :friend_id, :user_id
  
  

end

app/models/twit.rb
class Twit < ActiveRecord::Base
  attr_accessible :created_at, :message, :user_id
  belongs_to :user
  validates_presence_of :message, :created_at, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  include Gravtastic
  gravtastic :size => 50 


  attr_accessible :username, :email, :password, :password_confirmation
  
  has_many :twits, :dependent => :destroy
  has_many :friendships
  has_many :friends, :through => :friendships

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  

  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  def add_friend(friend)
   
    friendship = friendships.build(:friend_id => friend.id)
      if !friendship.save
        logger.debug "User '#{friend.email}' is already a friend"
      end
  end  

  def remove_friend(friend)
    friendship = Friendship.find(:all, :conditions => ["user_id = ? and friend_id = ?", self.id, friend.id])
    friendship = friendships.find_by_friend_id(friend.id)
      if friendship
        friendship.destroy
      end
  end  

  def is_friend?(friend)
    return self.friends.include? friend
  end

  def all_twits
    alltwits = Twit.find(:all, :conditions => ['user_id in (?)', friends.map(&:id).push(self.id)], :order => "created_at desc")
    alltwits ||= "No twits yet"
  end  

  def self.search(search_query)
    if search_query
      where('username LIKE ?', search_query ).to_sql
    else
      nil
    end

  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :login_required  

	def index
    @twits = current_user.all_twits
      if current_user.twits.last == nil
        @last_twit = "no messages yet."
      else
        @last_twit = "Latest:  #{current_user.twits.last.message}"
      end
    @search_result = User.search(params[:search_query])
    render "home/search" if @search_result.blank?

	end	

	def show
    @user = User.find_by_username(params[:username])
      if @user.username == current_user.username 
        redirect_to root_path
      end
    @twits = @user.all_twits
	end	
 

  def do_follow
    @user = User.find_by_username(params[:username])
      if current_user.is_friend? @user 
        current_user.remove_friend(@user) 
        flash[:notice] = "You are no longer friends with #{@user.username}."
        
      else
        current_user.add_friend(@user)  
        flash[:notice] = "#{@user.username} is your friend now." 
        
      end
        redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_filter :login_required 

  def create
  	twit = current_user.twits.build(params[:twit])
  	  if twit.message.blank?
        flash[:error] = "Message can't be blank!"
      else
        twit.created_at = Time.now
        twit.save!
      end
    redirect_to root_path
  end

  def destroy
    @twit = current_user.twits.find(params[:id])
    @twit.destroy
    redirect_to root_path
  end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/_twits_list.html.erb
 <ul id="twits_list">

  <% @twits.each do |t| %>

    <li <% if @twits.first == t %> class = "first" <%end%>>

      <%= image_tag t.user.gravatar_url %>

      <div class = "twit_message_container">

      <%= h link_to t.user.username, user_path(t.user.username) %>	
      <%= h t.message %>

      <% if t.user_id == current_user.id %>
      <%= link_to "Delete", t, :confirm => "You sure?", :method => :delete %>
      <% end %>

     

      <div class = 'time_ago'>
      Created: <%= distance_of_time_in_words_to_now(t.created_at) %> ago
      
      <% if t.user.username != current_user.username %>
        <% if current_user.is_friend? t.user%>
          
            <input type = "button" name = "<%= t.user.username %>" value = "unfollow" class = "button ajax_button"/>
          
         <% else %>
            <input type = "button" name = "<%= t.user.username %>" value = "follow" class = "button ajax_button"/>
        <% end %>
      <% end %>

      </div>

      

      </div>
      <div class = "clear"></div>
    
    </li>
  <%end%>
</ul>

<script type="text/javascript">
  $(function() {
    $('.ajax_button').click(function(){
      $.ajax({
        type: "Get",
        url: "/user/" + $(this).attr('name') + "/do_follow",
         this.set('value','Unfollow');
           })

    })
  })
</script>

app/views/home/index.html.erb
<script type="text/javascript">
$(function() {
$('#twit_message').keyup(function(){
var message_length = $(this).val().length;

var remaining = 140 - message_length;
var mes = "Chars remain: "
$('#char_count').html(mes + remaining);
 }) })
</script>


  <%= form_for Twit.new do |t| %>  
  
  <div id="twit_form"> 

  <h3 ><%= "What are you doing, #{current_user.username} ?" %></h3>
  <div id="char_count"></div>

  <%= t.text_area :message %> 
  
  <div class="clear"></div>

  <div id ="submit_button_container">
    <%= t.submit "Post", :class => "submit"%>
  </div> 

  <div id="latest_message">
  <%= h @last_twit %>
  </div>

  <div class="clear"></div>

 
  <div class="clear"></div>
  </div>
  
  <% end %>

  <%= render "twits_list" %>

 

app/views/home/search.html.erb
<% @search_result %>

app/views/home/show.html.erb
<h1> <%= image_tag @user.gravatar_url, :align => 'top' %> <%= @user.username %></h1>


  <%= form_tag("/users/#{@user.username}/do_follow")  do |f| %>  

    <div id = "submit_button_container">

  	<% if current_user.is_friend? @user %>
      <%= submit_tag  "Unfollow" , :class => "submit" %>
    <% else %>
      <%= submit_tag  "Follow" , :class => "submit" %>

    <% end %>
    </div> 

  <div class="clear"></div>
  <% end %>

<hr>
<%= render "twits_list", :locals => {:twits => @twits}  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <div id="header"></div>

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="main">
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>


      </div>

   
    <% if current_user %>
     <%= render :partial => "/partials/side_content" %>
    <% end %>
  

   <div class="clear"></div>
      

    </div>
  
  <div class="footer"><div class="shell"></div></div>

  </body>
</html>

app/views/partials/_side_content.html.erb
<div id="side">
<div class="sidecontent"><%= image_tag current_user.gravatar_url(:size => 30) %>

 <div class="stats"> 
   <%= current_user.username %>
   <br>
   <%= "Number of tweets: #{current_user.twits.count}" %>
  </div>
</div>

<div class="followers">

<%= "Following: #{current_user.friends.count}" %> </div>

<div class="follow_avs">
  <% current_user.friends.each do |friend| %>
    <% if friend != current_user %> 
    <%= link_to image_tag(friend.gravatar_url(:size => 20)), user_path(friend.username) %>
    <%end%>
  <% end %>
</div>

<div class = "search">
  <%= form_tag root_path, :method => 'get' do %>
  <%= text_field_tag :search_query %>
  <%= submit_tag "Search", :name => nil %>
</div>

<%end%>

</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/welcome/index.html.erb
<h1>Welcome!!!</h1>